#!/bin/bash

set -ouex pipefail

FRELEASE=$(rpm -E %fedora)

# Enable staging for supergfxctl if repo file exists
if [[ -f /etc/yum.repos.d/_copr_ublue-os-staging.repo ]]; then
    sed -i 's@enabled=0@enabled=1@g' /etc/yum.repos.d/_copr_ublue-os-staging.repo
else
    # Otherwise, retrieve the repo file for staging
    curl -Lo /etc/yum.repos.d/_copr_ublue-os-staging.repo https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-"${FRELEASE}"/ublue-os-staging-fedora-"${FRELEASE}".repo
fi

if [[ "${BASE_IMAGE_NAME}" == "kinoite" ]]; then
    VARIANT_PKGS="supergfxctl"
elif [[ "${BASE_IMAGE_NAME}" == "silverblue" ]]; then
    VARIANT_PKGS="supergfxctl"
else
    VARIANT_PKGS=""
fi

dnf5 install -y \
    /rpms/nvidia/libnvidia-cfg-* \
    /rpms/nvidia/libnvidia-fbc-* \
    /rpms/nvidia/libnvidia-gpucomp-* \
    /rpms/nvidia/libnvidia-ml-* \
    /rpms/nvidia/nvidia-libXNVCtrl-5* \
    /rpms/nvidia/nvidia-settings-5* \
    /rpms/nvidia/nvidia-driver-* \
    /rpms/nvidia/nvidia-kmod-common-* \
    /rpms/nvidia/nvidia-modprobe-5* \
    /rpms/nvidia/nvidia-persistenced-5* \
    /rpms/nvidia/xorg-x11* \
    /rpms/nvidia/nvidia-container-toolkit-1* \
    /rpms/nvidia/nvidia-container-toolkit-base-1* \
    /rpms/nvidia/libnvidia-container1-1* \
    /rpms/nvidia/libnvidia-container-tools-1* \
    libva-nvidia-driver \
    ${VARIANT_PKGS}

# Disable staging
sed -i 's@enabled=1@enabled=0@g' /etc/yum.repos.d/_copr_ublue-os-staging.repo

systemctl enable ublue-nvctk-cdi.service
semodule --verbose --install /usr/share/selinux/packages/nvidia-container.pp

# Universal Blue specific Initramfs fixes
if [[ -f /etc/modprobe.d/nvidia-modeset.conf ]]; then
    install -Dpm0644 /etc/modprobe.d/nvidia-modeset.conf /usr/lib/modprobe.d/nvidia-modeset.conf
elif [[ -f /usr/lib/modprobe.d/nvidia-modeset.conf ]]; then
    echo "Using existing /usr/lib/modprobe.d/nvidia-modeset.conf"
else
    install -Dpm0644 /dev/null /usr/lib/modprobe.d/nvidia-modeset.conf
    cat <<'EOF' > /usr/lib/modprobe.d/nvidia-modeset.conf
# Nvidia modesetting support. Set to 0 or comment to disable kernel modesetting
# support. This must be disabled in case of SLI Mosaic.

options nvidia-drm modeset=1
EOF
fi

if [[ -f /usr/lib/dracut/dracut.conf.d/99-nvidia.conf ]]; then
    echo "Using existing /usr/lib/dracut/dracut.conf.d/99-nvidia.conf"
else
    install -Dpm0644 /dev/null /usr/lib/dracut/dracut.conf.d/99-nvidia.conf
    cat <<'EOF' > /usr/lib/dracut/dracut.conf.d/99-nvidia.conf
# Omit the i915 amdgpu nvidia driver from the ramdisk, to avoid needing to regenerate
# the ramdisk on updates.
force_drivers+=" i915 amdgpu nvidia nvidia_drm nvidia_modeset nvidia_peermem nvidia_uvm "
EOF
fi





# Awful hack of an install method to restore VK_hdr_layer in a way that won't randomly break for the foreseeable future.
PKG="VK_hdr_layer"
TMPDIR="$(mktemp -d)"

dnf download "${PKG}" --destdir "$TMPDIR"

RPM_FILE=$(ls "$TMPDIR"/*.rpm)
mkdir "$TMPDIR/$PKG"
cd "$TMPDIR/$PKG"

# Extract RPM
rpm2cpio "$RPM_FILE" | cpio -idmv

# Libraries
mkdir -p /usr/lib64/${PKG}
cp -v usr/lib64/${PKG}/* /usr/lib64/${PKG}/

# Vulkan implicit layer
mkdir -p /usr/share/vulkan/implicit_layer.d
cp -v usr/share/vulkan/implicit_layer.d/VkLayer_hdr_wsi.*.json \
    /usr/share/vulkan/implicit_layer.d/

# License & Docs
mkdir -p /usr/share/licenses/${PKG}
cp -v usr/share/licenses/${PKG}/* /usr/share/licenses/${PKG}/
mkdir -p /usr/share/doc/${PKG}
cp -v usr/share/doc/${PKG}/* /usr/share/doc/${PKG}/